'use strict';window.DOMHandler=class{constructor(c,f){this._iRuntime=c;this._componentId=f;this._hasTickCallback=!1;this._tickCallback=()=>this.Tick()}Attach(){}PostToRuntime(c,f,g,k){this._iRuntime.PostToRuntimeComponent(this._componentId,c,f,g,k)}PostToRuntimeAsync(c,f,g,k){return this._iRuntime.PostToRuntimeComponentAsync(this._componentId,c,f,g,k)}_PostToRuntimeMaybeSync(c,f,g){this._iRuntime.UsesWorker()?this.PostToRuntime(c,f,g):this._iRuntime._GetLocalRuntime()._OnMessageFromDOM({type:"event",
component:this._componentId,handler:c,dispatchOpts:g||null,data:f,responseId:null})}AddRuntimeMessageHandler(c,f){this._iRuntime.AddRuntimeComponentMessageHandler(this._componentId,c,f)}AddRuntimeMessageHandlers(c){for(const [f,g]of c)this.AddRuntimeMessageHandler(f,g)}GetRuntimeInterface(){return this._iRuntime}GetComponentID(){return this._componentId}_StartTicking(){this._hasTickCallback||(this._iRuntime._AddRAFCallback(this._tickCallback),this._hasTickCallback=!0)}_StopTicking(){this._hasTickCallback&&
(this._iRuntime._RemoveRAFCallback(this._tickCallback),this._hasTickCallback=!1)}Tick(){}};
window.RateLimiter=class{constructor(c,f){this._callback=c;this._interval=f;this._timerId=-1;this._lastCallTime=-Infinity;this._timerCallFunc=()=>this._OnTimer();this._canRunImmediate=this._ignoreReset=!1}SetCanRunImmediate(c){this._canRunImmediate=!!c}Call(){if(-1===this._timerId){var c=Date.now(),f=c-this._lastCallTime,g=this._interval;f>=g&&this._canRunImmediate?(this._lastCallTime=c,this._RunCallback()):this._timerId=self.setTimeout(this._timerCallFunc,Math.max(g-f,4))}}_RunCallback(){this._ignoreReset=
!0;this._callback();this._ignoreReset=!1}Reset(){this._ignoreReset||(this._CancelTimer(),this._lastCallTime=Date.now())}_OnTimer(){this._timerId=-1;this._lastCallTime=Date.now();this._RunCallback()}_CancelTimer(){-1!==this._timerId&&(self.clearTimeout(this._timerId),this._timerId=-1)}Release(){this._CancelTimer();this._timerCallFunc=this._callback=null}};"use strict";
window.DOMElementHandler=class extends self.DOMHandler{constructor(c,f){super(c,f);this._elementMap=new Map;this._autoAttach=!0;this.AddRuntimeMessageHandlers([["create",g=>this._OnCreate(g)],["destroy",g=>this._OnDestroy(g)],["set-visible",g=>this._OnSetVisible(g)],["update-position",g=>this._OnUpdatePosition(g)],["update-state",g=>this._OnUpdateState(g)],["focus",g=>this._OnSetFocus(g)],["set-css-style",g=>this._OnSetCssStyle(g)],["set-attribute",g=>this._OnSetAttribute(g)],["remove-attribute",
g=>this._OnRemoveAttribute(g)]]);this.AddDOMElementMessageHandler("get-element",g=>g)}SetAutoAttach(c){this._autoAttach=!!c}AddDOMElementMessageHandler(c,f){this.AddRuntimeMessageHandler(c,g=>{const k=this._elementMap.get(g.elementId);return f(k,g)})}_OnCreate(c){const f=c.elementId,g=this.CreateElement(f,c);this._elementMap.set(f,g);c.isVisible||(g.style.display="none");c=this._GetFocusElement(g);c.addEventListener("focus",k=>this._OnFocus(f));c.addEventListener("blur",k=>this._OnBlur(f));this._autoAttach&&
document.body.appendChild(g)}CreateElement(c,f){throw Error("required override");}DestroyElement(c){}_OnDestroy(c){c=c.elementId;const f=this._elementMap.get(c);this.DestroyElement(f);this._autoAttach&&f.parentElement.removeChild(f);this._elementMap.delete(c)}PostToRuntimeElement(c,f,g){g||(g={});g.elementId=f;this.PostToRuntime(c,g)}_PostToRuntimeElementMaybeSync(c,f,g){g||(g={});g.elementId=f;this._PostToRuntimeMaybeSync(c,g)}_OnSetVisible(c){this._autoAttach&&(this._elementMap.get(c.elementId).style.display=
c.isVisible?"":"none")}_OnUpdatePosition(c){if(this._autoAttach){var f=this._elementMap.get(c.elementId);f.style.left=c.left+"px";f.style.top=c.top+"px";f.style.width=c.width+"px";f.style.height=c.height+"px";c=c.fontSize;null!==c&&(f.style.fontSize=c+"em")}}_OnUpdateState(c){const f=this._elementMap.get(c.elementId);this.UpdateState(f,c)}UpdateState(c,f){throw Error("required override");}_GetFocusElement(c){return c}_OnFocus(c){this.PostToRuntimeElement("elem-focused",c)}_OnBlur(c){this.PostToRuntimeElement("elem-blurred",
c)}_OnSetFocus(c){const f=this._GetFocusElement(this._elementMap.get(c.elementId));c.focus?f.focus():f.blur()}_OnSetCssStyle(c){this._elementMap.get(c.elementId).style[c.prop]=c.val}_OnSetAttribute(c){this._elementMap.get(c.elementId).setAttribute(c.name,c.val)}_OnRemoveAttribute(c){this._elementMap.get(c.elementId).removeAttribute(c.name)}GetElementById(c){return this._elementMap.get(c)}};"use strict";
{const c=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);function f(b,a){const d=document.createElement("script");d.async=!1;"module"===a&&(d.type="module");if(b.isStringSrc)d.textContent=b.str,document.head.appendChild(d);else return new Promise((e,h)=>{d.onload=e;d.onerror=h;d.src=b;document.head.appendChild(d)})}let g=!1,k=!1;function m(){if(!g){try{new Worker("blob://",{get type(){k=!0}})}catch(b){}g=!0}return k}let r=new Audio;const u={"audio/webm; codecs=opus":!!r.canPlayType("audio/webm; codecs=opus"),
"audio/ogg; codecs=opus":!!r.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!r.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!r.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!r.canPlayType("audio/mp4"),"audio/mpeg":!!r.canPlayType("audio/mpeg")};r=null;async function D(b){b=await v(b);return(new TextDecoder("utf-8")).decode(b)}function v(b){return new Promise((a,d)=>{const e=new FileReader;e.onload=h=>a(h.target.result);e.onerror=h=>d(h);e.readAsArrayBuffer(b)})}
const z=[];let x=0;window.RealFile=window.File;const w=[],A=new Map,q=new Map;let B=0;const y=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");y.push(b)};const E=new Set(["cordova","playable-ad","instant-games"]);function C(b){return E.has(b)}window.RuntimeInterface=class b{constructor(a){this._useWorker=a.useWorker;this._messageChannelPort=null;this._baseUrl="";this._scriptFolder=a.scriptFolder;this._scriptsType=a.scriptsType;this._workerScriptURLs=
{};this._localRuntime=this._worker=null;this._domHandlers=[];this._jobScheduler=this._canvas=this._runtimeDomHandler=null;this._rafId=-1;this._rafFunc=()=>this._OnRAFCallback();this._rafCallbacks=[];this._exportType=a.exportType;!this._useWorker||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&("module"!==this._scriptsType||m())||(this._useWorker=!1);C(this._exportType)&&this._useWorker&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),
this._useWorker=!1);this._localFileStrings=this._localFileBlobs=null;"html5"!==this._exportType&&"playable-ad"!==this._exportType||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.AddRuntimeComponentMessageHandler("runtime","cordova-fetch-local-file",d=>this._OnCordovaFetchLocalFile(d));this.AddRuntimeComponentMessageHandler("runtime","create-job-worker",
d=>this._OnCreateJobWorker(d));"cordova"===this._exportType?document.addEventListener("deviceready",()=>this._Init(a)):this._Init(a)}Release(){this._CancelAnimationFrame();this._messageChannelPort&&(this._messageChannelPort=this._messageChannelPort.onmessage=null);this._worker&&(this._worker.terminate(),this._worker=null);this._localRuntime&&(this._localRuntime.Release(),this._localRuntime=null);this._canvas&&(this._canvas.parentElement.removeChild(this._canvas),this._canvas=null)}GetCanvas(){return this._canvas}GetBaseURL(){return this._baseUrl}UsesWorker(){return this._useWorker}GetExportType(){return this._exportType}GetScriptFolder(){return this._scriptFolder}IsiOSCordova(){return c&&
"cordova"===this._exportType}IsiOSWebView(){return c&&C(this._exportType)||navigator.standalone}async _Init(a){if("playable-ad"===this._exportType){this._localFileBlobs=self.c3_base64files;this._localFileStrings={};await this._ConvertDataUrisToBlobs();for(let e=0,h=a.engineScripts.length;e<h;++e){var d=a.engineScripts[e].toLowerCase();this._localFileStrings.hasOwnProperty(d)?a.engineScripts[e]={isStringSrc:!0,str:this._localFileStrings[d]}:this._localFileBlobs.hasOwnProperty(d)&&(a.engineScripts[e]=
URL.createObjectURL(this._localFileBlobs[d]))}}a.baseUrl?this._baseUrl=a.baseUrl:(d=location.origin,this._baseUrl=("null"===d?"file:///":d)+location.pathname,d=this._baseUrl.lastIndexOf("/"),-1!==d&&(this._baseUrl=this._baseUrl.substr(0,d+1)));a.workerScripts&&(this._workerScriptURLs=a.workerScripts);d=new MessageChannel;this._messageChannelPort=d.port1;this._messageChannelPort.onmessage=e=>this._OnMessageFromRuntime(e.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(e=>this._OnMessageFromDebugger(e));
this._jobScheduler=new self.JobSchedulerDOM(this);await this._jobScheduler.Init();this.MaybeForceBodySize();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this._useWorker?await this._InitWorker(a,d.port2):await this._InitDOM(a,d.port2)}_GetWorkerURL(a){a=this._workerScriptURLs.hasOwnProperty(a)?this._workerScriptURLs[a]:a.endsWith("/workermain.js")&&this._workerScriptURLs.hasOwnProperty("workermain.js")?
this._workerScriptURLs["workermain.js"]:"playable-ad"===this._exportType&&this._localFileBlobs.hasOwnProperty(a.toLowerCase())?this._localFileBlobs[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async CreateWorker(a,d,e){if(a.startsWith("blob:"))return new Worker(a,e);if(this.IsiOSCordova()&&"file:"===location.protocol)return a=await this.CordovaFetchLocalFileAsArrayBuffer(this._scriptFolder+a),a=new Blob([a],{type:"application/javascript"}),new Worker(URL.createObjectURL(a),
e);a=new URL(a,d);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),e)}return new Worker(a,e)}_GetWindowInnerWidth(){return Math.max(window.innerWidth,1)}_GetWindowInnerHeight(){return Math.max(window.innerHeight,1)}MaybeForceBodySize(){if(this.IsiOSWebView()){const a=document.documentElement.style,d=document.body.style,e=window.innerWidth<window.innerHeight,h=e?window.screen.width:window.screen.height;
d.height=a.height=(e?window.screen.height:window.screen.width)+"px";d.width=a.width=h+"px"}}_GetCommonRuntimeOptions(a){return{baseUrl:this._baseUrl,windowInnerWidth:this._GetWindowInnerWidth(),windowInnerHeight:this._GetWindowInnerHeight(),devicePixelRatio:window.devicePixelRatio,isFullscreen:b.IsDocumentFullscreen(),projectData:a.projectData,scriptsType:a.scriptsType,previewImageBlobs:window.cr_previewImageBlobs||this._localFileBlobs,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileUrls:window.cr_previewProjectFiles,
swClientId:window.cr_swClientId||"",exportType:a.exportType,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.ife,jobScheduler:this._jobScheduler.GetPortData(),supportedAudioFormats:u,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this._scriptFolder+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this._scriptFolder+"opus.wasm.wasm",isiOSCordova:this.IsiOSCordova(),isiOSWebView:this.IsiOSWebView(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async _InitWorker(a,
d){var e=this._GetWorkerURL(a.workerMainUrl);this._worker=await this.CreateWorker(e,this._baseUrl,{type:this._scriptsType,name:"Runtime"});this._canvas=document.createElement("canvas");this._canvas.style.display="none";e=this._canvas.transferControlToOffscreen();document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._worker.postMessage(Object.assign(this._GetCommonRuntimeOptions(a),{type:"init-runtime",isInWorker:!0,messagePort:d,canvas:e,workerDependencyScripts:a.workerDependencyScripts||
[],engineScripts:a.engineScripts,projectScripts:a.projectScripts,mainProjectScript:a.mainProjectScript,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[d,e,...this._jobScheduler.GetPortTransferables()]);this._domHandlers=w.map(h=>new h(this));this._FindRuntimeDOMHandler();self.c3_callFunction=(h,l)=>this._runtimeDomHandler._InvokeFunctionFromJS(h,l);"preview"===this._exportType&&(self.goToLastErrorScript=()=>this.PostToRuntimeComponent("runtime","go-to-last-error-script"))}async _InitDOM(a,d){this._canvas=
document.createElement("canvas");this._canvas.style.display="none";document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._domHandlers=w.map(l=>new l(this));this._FindRuntimeDOMHandler();var e=a.engineScripts.map(l=>"string"===typeof l?(new URL(l,this._baseUrl)).toString():l);Array.isArray(a.workerDependencyScripts)&&e.unshift(...a.workerDependencyScripts);e=await Promise.all(e.map(l=>this._MaybeGetCordovaScriptURL(l,this._scriptsType)));await Promise.all(e.map(l=>f(l,this._scriptsType)));
const h=self.C3_ProjectScriptsStatus;if("module"===this._scriptsType){e=a.mainProjectScript;const l=a.projectScripts;for(let [p,n]of l)if(n||(n=p),p===e)try{n=await this._MaybeGetCordovaScriptURL(n,this._scriptsType),await f(n,this._scriptsType),"preview"!==this._exportType||h[p]||this._ReportProjectMainScriptError(p,"main script did not run to completion")}catch(t){this._ReportProjectMainScriptError(p,t)}else if("scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))n=await this._MaybeGetCordovaScriptURL(n,
this._scriptsType),await f(n,this._scriptsType)}else if(a.projectScripts&&0<a.projectScripts.length)try{if(await Promise.all(a.projectScripts.map(l=>f(l[1],this._scriptsType))),Object.values(h).some(l=>!l)){self.setTimeout(()=>this._ReportProjectScriptError(h),100);return}}catch(l){console.error("[Preview] Error loading project scripts: ",l);self.setTimeout(()=>this._ReportProjectScriptError(h),100);return}"preview"===this._exportType&&"object"!==typeof self.C3.ScriptsInEvents?(this._RemoveLoadingMessage(),
console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this._GetCommonRuntimeOptions(a),{isInWorker:!1,messagePort:d,canvas:this._canvas,runOnStartupFunctions:y}),this._OnBeforeCreateRuntime(),this._localRuntime=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this._localRuntime,a))}_ReportProjectScriptError(a){this._RemoveLoadingMessage();
a=`Failed to load project script '${Object.entries(a).filter(d=>!d[1]).map(d=>d[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+a);alert(a)}_ReportProjectMainScriptError(a,d){this._RemoveLoadingMessage();console.error(`[Preview] Failed to load project main script (${a}): `,d);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}_OnBeforeCreateRuntime(){this._RemoveLoadingMessage()}_RemoveLoadingMessage(){const a=
window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async _OnCreateJobWorker(a){a=await this._jobScheduler._CreateJobWorker();return{outputPort:a,transferables:[a]}}_GetLocalRuntime(){if(this._useWorker)throw Error("not available in worker mode");return this._localRuntime}PostToRuntimeComponent(a,d,e,h,l){this._messageChannelPort.postMessage({type:"event",component:a,handler:d,dispatchOpts:h||null,data:e,responseId:null},l)}PostToRuntimeComponentAsync(a,
d,e,h,l){const p=B++,n=new Promise((t,F)=>{q.set(p,{resolve:t,reject:F})});this._messageChannelPort.postMessage({type:"event",component:a,handler:d,dispatchOpts:h||null,data:e,responseId:p},l);return n}["_OnMessageFromRuntime"](a){const d=a.type;if("event"===d)return this._OnEventFromRuntime(a);if("result"===d)this._OnResultFromRuntime(a);else if("runtime-ready"===d)this._OnRuntimeReady();else if("alert-error"===d)this._RemoveLoadingMessage(),alert(a.message);else if("creating-runtime"===d)this._OnBeforeCreateRuntime();
else throw Error(`unknown message '${d}'`);}_OnEventFromRuntime(a){const d=a.component,e=a.handler,h=a.data,l=a.responseId;if(a=A.get(d))if(a=a.get(e)){var p=null;try{p=a(h)}catch(n){console.error(`Exception in '${d}' handler '${e}':`,n);null!==l&&this._PostResultToRuntime(l,!1,""+n);return}if(null===l)return p;p&&p.then?p.then(n=>this._PostResultToRuntime(l,!0,n)).catch(n=>{console.error(`Rejection from '${d}' handler '${e}':`,n);this._PostResultToRuntime(l,!1,""+n)}):this._PostResultToRuntime(l,
!0,p)}else console.warn(`[DOM] No handler '${e}' for component '${d}'`);else console.warn(`[DOM] No event handlers for component '${d}'`)}_PostResultToRuntime(a,d,e){let h;e&&e.transferables&&(h=e.transferables);this._messageChannelPort.postMessage({type:"result",responseId:a,isOk:d,result:e},h)}_OnResultFromRuntime(a){const d=a.responseId,e=a.isOk;a=a.result;const h=q.get(d);e?h.resolve(a):h.reject(a);q.delete(d)}AddRuntimeComponentMessageHandler(a,d,e){let h=A.get(a);h||(h=new Map,A.set(a,h));if(h.has(d))throw Error(`[DOM] Component '${a}' already has handler '${d}'`);
h.set(d,e)}static AddDOMHandlerClass(a){if(w.includes(a))throw Error("DOM handler already added");w.push(a)}_FindRuntimeDOMHandler(){for(const a of this._domHandlers)if("runtime"===a.GetComponentID()){this._runtimeDomHandler=a;return}throw Error("cannot find runtime DOM handler");}_OnMessageFromDebugger(a){this.PostToRuntimeComponent("debugger","message",a)}_OnRuntimeReady(){for(const a of this._domHandlers)a.Attach()}static IsDocumentFullscreen(){return!!(document.fullscreenElement||document.webkitFullscreenElement||
document.mozFullScreenElement)}async GetRemotePreviewStatusInfo(){return await this.PostToRuntimeComponentAsync("runtime","get-remote-preview-status-info")}_AddRAFCallback(a){this._rafCallbacks.push(a);this._RequestAnimationFrame()}_RemoveRAFCallback(a){a=this._rafCallbacks.indexOf(a);if(-1===a)throw Error("invalid callback");this._rafCallbacks.splice(a,1);this._rafCallbacks.length||this._CancelAnimationFrame()}_RequestAnimationFrame(){-1===this._rafId&&this._rafCallbacks.length&&(this._rafId=requestAnimationFrame(this._rafFunc))}_CancelAnimationFrame(){-1!==
this._rafId&&(cancelAnimationFrame(this._rafId),this._rafId=-1)}_OnRAFCallback(){this._rafId=-1;for(const a of this._rafCallbacks)a();this._RequestAnimationFrame()}TryPlayMedia(a){this._runtimeDomHandler.TryPlayMedia(a)}RemovePendingPlay(a){this._runtimeDomHandler.RemovePendingPlay(a)}_PlayPendingMedia(){this._runtimeDomHandler._PlayPendingMedia()}SetSilent(a){this._runtimeDomHandler.SetSilent(a)}IsAudioFormatSupported(a){return!!u[a]}async _WasmDecodeWebMOpus(a){a=await this.PostToRuntimeComponentAsync("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}IsAbsoluteURL(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}IsRelativeURL(a){return!this.IsAbsoluteURL(a)}async _MaybeGetCordovaScriptURL(a,d){return"cordova"===this._exportType&&"module"===d&&(a.startsWith("file:")||"file:"===location.protocol&&this.IsRelativeURL(a))?(a.startsWith(this._baseUrl)&&(a=a.substr(this._baseUrl.length)),a=await this.CordovaFetchLocalFileAsArrayBuffer(a),a=new Blob([a],
{type:"application/javascript"}),URL.createObjectURL(a)):a}async _OnCordovaFetchLocalFile(a){const d=a.filename;switch(a.as){case "text":return await this.CordovaFetchLocalFileAsText(d);case "buffer":return await this.CordovaFetchLocalFileAsArrayBuffer(d);default:throw Error("unsupported type");}}_GetPermissionAPI(){const a=window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof a)throw Error("Permission API is not loaded");return a}_MapPermissionID(a,d){a=
a[d];if("string"!==typeof a)throw Error("Invalid permission name");return a}_HasPermission(a){const d=this._GetPermissionAPI();return new Promise((e,h)=>d.checkPermission(this._MapPermissionID(d,a),l=>e(!!l.hasPermission),h))}_RequestPermission(a){const d=this._GetPermissionAPI();return new Promise((e,h)=>d.requestPermission(this._MapPermissionID(d,a),l=>e(!!l.hasPermission),h))}async RequestPermissions(a){if("cordova"!==this.GetExportType()||this.IsiOSCordova())return!0;for(const d of a)if(!await this._HasPermission(d)&&
!1===await this._RequestPermission(d))return!1;return!0}async RequirePermissions(...a){if(!1===await this.RequestPermissions(a))throw Error("Permission not granted");}CordovaFetchLocalFile(a){const d=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((e,h)=>{window.resolveLocalFileSystemURL(d,l=>{l.file(e,h)},h)})}async CordovaFetchLocalFileAsText(a){a=await this.CordovaFetchLocalFile(a);return await D(a)}_CordovaMaybeStartNextArrayBufferRead(){if(z.length&&!(8<=x)){x++;
var a=z.shift();this._CordovaDoFetchLocalFileAsAsArrayBuffer(a.filename,a.successCallback,a.errorCallback)}}CordovaFetchLocalFileAsArrayBuffer(a){return new Promise((d,e)=>{z.push({filename:a,successCallback:h=>{x--;this._CordovaMaybeStartNextArrayBufferRead();d(h)},errorCallback:h=>{x--;this._CordovaMaybeStartNextArrayBufferRead();e(h)}});this._CordovaMaybeStartNextArrayBufferRead()})}async _CordovaDoFetchLocalFileAsAsArrayBuffer(a,d,e){try{const h=await this.CordovaFetchLocalFile(a),l=await v(h);
d(l)}catch(h){e(h)}}async _ConvertDataUrisToBlobs(){const a=[];for(const [d,e]of Object.entries(this._localFileBlobs))a.push(this._ConvertDataUriToBlobs(d,e));await Promise.all(a)}async _ConvertDataUriToBlobs(a,d){if("object"===typeof d)this._localFileBlobs[a]=new Blob([d.str],{type:d.type}),this._localFileStrings[a]=d.str;else{let e=await this._FetchDataUri(d);e||(e=this._DataURIToBinaryBlobSync(d));this._localFileBlobs[a]=e}}async _FetchDataUri(a){try{return await (await fetch(a)).blob()}catch(d){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
d),null}}_DataURIToBinaryBlobSync(a){a=this._ParseDataURI(a);return this._BinaryStringToBlob(a.data,a.mime_type)}_ParseDataURI(a){var d=a.indexOf(",");if(0>d)throw new URIError("expected comma in data: uri");var e=a.substring(5,d);a=a.substring(d+1);d=e.split(";");e=d[0]||"";const h=d[2];a="base64"===d[1]||"base64"===h?atob(a):decodeURIComponent(a);return{mime_type:e,data:a}}_BinaryStringToBlob(a,d){var e=a.length;let h=e>>2,l=new Uint8Array(e),p=new Uint32Array(l.buffer,0,h),n,t;for(t=n=0;n<h;++n)p[n]=
a.charCodeAt(t++)|a.charCodeAt(t++)<<8|a.charCodeAt(t++)<<16|a.charCodeAt(t++)<<24;for(e&=3;e--;)l[t]=a.charCodeAt(t),++t;return new Blob([l],{type:d})}}}"use strict";
{const c=self.RuntimeInterface;function f(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const g=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),k={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},m={dispatchUserScriptEvent:!0},r={dispatchRuntimeEvent:!0};function u(b){return new Promise((a,d)=>{const e=document.createElement("link");e.onload=()=>a(e);e.onerror=
h=>d(h);e.rel="stylesheet";e.href=b;document.head.appendChild(e)})}function D(b){return new Promise((a,d)=>{const e=new Image;e.onload=()=>a(e);e.onerror=h=>d(h);e.src=b})}async function v(b){b=URL.createObjectURL(b);try{return await D(b)}finally{URL.revokeObjectURL(b)}}function z(b){return new Promise((a,d)=>{let e=new FileReader;e.onload=h=>a(h.target.result);e.onerror=h=>d(h);e.readAsText(b)})}async function x(b,a,d){if(!/firefox/i.test(navigator.userAgent))return await v(b);var e=await z(b);e=
(new DOMParser).parseFromString(e,"image/svg+xml");const h=e.documentElement;if(h.hasAttribute("width")&&h.hasAttribute("height")){const l=h.getAttribute("width"),p=h.getAttribute("height");if(!l.includes("%")&&!p.includes("%"))return await v(b)}h.setAttribute("width",a+"px");h.setAttribute("height",d+"px");e=(new XMLSerializer).serializeToString(e);b=new Blob([e],{type:"image/svg+xml"});return await v(b)}function w(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);
return!1}const A=new Set(["canvas","body","html"]);function q(b){const a=b.target.tagName.toLowerCase();A.has(a)&&b.preventDefault()}function B(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}self.C3_GetSvgImageSize=async function(b){b=await v(b);if(0<b.width&&0<b.height)return[b.width,b.height];{b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]}};
self.C3_RasterSvgImageBlob=async function(b,a,d,e,h){b=await x(b,a,d);const l=document.createElement("canvas");l.width=e;l.height=h;l.getContext("2d").drawImage(b,0,0,a,d);return l};let y=!1;document.addEventListener("pause",()=>y=!0);document.addEventListener("resume",()=>y=!1);function E(){try{return window.parent&&window.parent.document.hasFocus()}catch(b){return!1}}function C(){const b=document.activeElement;if(!b)return!1;const a=b.tagName.toLowerCase(),d=new Set("email number password search tel text url".split(" "));
return"textarea"===a?!0:"input"===a?d.has(b.type.toLowerCase()||"text"):w(b)}c.AddDOMHandlerClass(class extends self.DOMHandler{constructor(b){super(b,"runtime");this._isFirstSizeUpdate=!0;this._simulatedResizeTimerId=-1;this._targetOrientation="any";this._attachedDeviceMotionEvent=this._attachedDeviceOrientationEvent=!1;this._lastPointerRawUpdateEvent=this._pointerRawUpdateRateLimiter=this._debugHighlightElem=null;b.AddRuntimeComponentMessageHandler("canvas","update-size",e=>this._OnUpdateCanvasSize(e));
b.AddRuntimeComponentMessageHandler("runtime","invoke-download",e=>this._OnInvokeDownload(e));b.AddRuntimeComponentMessageHandler("runtime","raster-svg-image",e=>this._OnRasterSvgImage(e));b.AddRuntimeComponentMessageHandler("runtime","get-svg-image-size",e=>this._OnGetSvgImageSize(e));b.AddRuntimeComponentMessageHandler("runtime","set-target-orientation",e=>this._OnSetTargetOrientation(e));b.AddRuntimeComponentMessageHandler("runtime","register-sw",()=>this._OnRegisterSW());b.AddRuntimeComponentMessageHandler("runtime",
"post-to-debugger",e=>this._OnPostToDebugger(e));b.AddRuntimeComponentMessageHandler("runtime","go-to-script",e=>this._OnPostToDebugger(e));b.AddRuntimeComponentMessageHandler("runtime","before-start-ticking",()=>this._OnBeforeStartTicking());b.AddRuntimeComponentMessageHandler("runtime","debug-highlight",e=>this._OnDebugHighlight(e));b.AddRuntimeComponentMessageHandler("runtime","enable-device-orientation",()=>this._AttachDeviceOrientationEvent());b.AddRuntimeComponentMessageHandler("runtime","enable-device-motion",
()=>this._AttachDeviceMotionEvent());b.AddRuntimeComponentMessageHandler("runtime","add-stylesheet",e=>this._OnAddStylesheet(e));b.AddRuntimeComponentMessageHandler("runtime","alert",e=>this._OnAlert(e));b.AddRuntimeComponentMessageHandler("runtime","hide-cordova-splash",()=>this._OnHideCordovaSplash());const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",e=>{const h=e.target,l=h.tagName.toLowerCase();a.has(l)||w(h)||e.preventDefault()});const d=b.GetCanvas();window.addEventListener("selectstart",
q);window.addEventListener("gesturehold",q);d.addEventListener("selectstart",q);d.addEventListener("gesturehold",q);window.addEventListener("touchstart",q,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",q,{passive:!1}),d.addEventListener("pointerdown",q)):d.addEventListener("touchstart",q);this._mousePointerLastButtons=0;window.addEventListener("mousedown",e=>{1===e.button&&e.preventDefault()});window.addEventListener("mousewheel",B,{passive:!1});window.addEventListener("wheel",
B,{passive:!1});window.addEventListener("resize",()=>this._OnWindowResize());b.IsiOSWebView()&&window.addEventListener("focusout",()=>{C()||(document.scrollingElement.scrollTop=0)});this._mediaPendingPlay=new Set;this._mediaRemovedPendingPlay=new WeakSet;this._isSilent=!1}_OnBeforeStartTicking(){"cordova"===this._iRuntime.GetExportType()?(document.addEventListener("pause",()=>this._OnVisibilityChange(!0)),document.addEventListener("resume",()=>this._OnVisibilityChange(!1))):document.addEventListener("visibilitychange",
()=>this._OnVisibilityChange(document.hidden));return{isSuspended:!(!document.hidden&&!y)}}Attach(){window.addEventListener("focus",()=>this._PostRuntimeEvent("window-focus"));window.addEventListener("blur",()=>{this._PostRuntimeEvent("window-blur",{parentHasFocus:E()});this._mousePointerLastButtons=0});window.addEventListener("fullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("webkitfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("mozfullscreenchange",
()=>this._OnFullscreenChange());window.addEventListener("fullscreenerror",a=>this._OnFullscreenError(a));window.addEventListener("webkitfullscreenerror",a=>this._OnFullscreenError(a));window.addEventListener("mozfullscreenerror",a=>this._OnFullscreenError(a));window.addEventListener("keydown",a=>this._OnKeyEvent("keydown",a));window.addEventListener("keyup",a=>this._OnKeyEvent("keyup",a));window.addEventListener("dblclick",a=>this._OnMouseEvent("dblclick",a,k));window.addEventListener("wheel",a=>
this._OnMouseWheelEvent("wheel",a));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{this._HandlePointerDownFocus(a);this._OnPointerEvent("pointerdown",a)}),this._iRuntime.UsesWorker()&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this._pointerRawUpdateRateLimiter=new self.RateLimiter(()=>this._DoSendPointerRawUpdate(),5),this._pointerRawUpdateRateLimiter.SetCanRunImmediate(!0),window.addEventListener("pointerrawupdate",a=>this._OnPointerRawUpdate(a))):
window.addEventListener("pointermove",a=>this._OnPointerEvent("pointermove",a)),window.addEventListener("pointerup",a=>this._OnPointerEvent("pointerup",a)),window.addEventListener("pointercancel",a=>this._OnPointerEvent("pointercancel",a))):(window.addEventListener("mousedown",a=>{this._HandlePointerDownFocus(a);this._OnMouseEventAsPointer("pointerdown",a)}),window.addEventListener("mousemove",a=>this._OnMouseEventAsPointer("pointermove",a)),window.addEventListener("mouseup",a=>this._OnMouseEventAsPointer("pointerup",
a)),window.addEventListener("touchstart",a=>{this._HandlePointerDownFocus(a);this._OnTouchEvent("pointerdown",a)}),window.addEventListener("touchmove",a=>this._OnTouchEvent("pointermove",a)),window.addEventListener("touchend",a=>this._OnTouchEvent("pointerup",a)),window.addEventListener("touchcancel",a=>this._OnTouchEvent("pointercancel",a)));const b=()=>this._PlayPendingMedia();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);
window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0)}_PostRuntimeEvent(b,a){this.PostToRuntime(b,a||null,r)}_GetWindowInnerWidth(){return this._iRuntime._GetWindowInnerWidth()}_GetWindowInnerHeight(){return this._iRuntime._GetWindowInnerHeight()}_OnWindowResize(){const b=this._GetWindowInnerWidth(),a=this._GetWindowInnerHeight();this._PostRuntimeEvent("window-resize",{innerWidth:b,innerHeight:a,devicePixelRatio:window.devicePixelRatio});this._iRuntime.IsiOSWebView()&&
(-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId),this._OnSimulatedResize(b,a,0))}_ScheduleSimulatedResize(b,a,d){-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId);this._simulatedResizeTimerId=setTimeout(()=>this._OnSimulatedResize(b,a,d),48)}_OnSimulatedResize(b,a,d){const e=this._GetWindowInnerWidth(),h=this._GetWindowInnerHeight();this._simulatedResizeTimerId=-1;e!=b||h!=a?this._PostRuntimeEvent("window-resize",{innerWidth:e,innerHeight:h,
devicePixelRatio:window.devicePixelRatio}):10>d&&this._ScheduleSimulatedResize(e,h,d+1)}_OnSetTargetOrientation(b){this._targetOrientation=b.targetOrientation}_TrySetTargetOrientation(){const b=this._targetOrientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?
a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",a)}}_OnFullscreenChange(){const b=c.IsDocumentFullscreen();b&&"any"!==this._targetOrientation&&this._TrySetTargetOrientation();this.PostToRuntime("fullscreenchange",{isFullscreen:b,innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnFullscreenError(b){console.warn("[Construct 3] Fullscreen request failed: ",
b);this.PostToRuntime("fullscreenerror",{isFullscreen:c.IsDocumentFullscreen(),innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnVisibilityChange(b){b?this._iRuntime._CancelAnimationFrame():this._iRuntime._RequestAnimationFrame();this.PostToRuntime("visibilitychange",{hidden:b})}_OnKeyEvent(b,a){"Backspace"===a.key&&q(a);const d=g.get(a.code)||a.code;this._PostToRuntimeMaybeSync(b,{code:d,key:a.key,which:a.which,repeat:a.repeat,altKey:a.altKey,ctrlKey:a.ctrlKey,
metaKey:a.metaKey,shiftKey:a.shiftKey,timeStamp:a.timeStamp},k)}_OnMouseWheelEvent(b,a){this.PostToRuntime(b,{clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},k)}_OnMouseEvent(b,a,d){f(a)||this._PostToRuntimeMaybeSync(b,{button:a.button,buttons:a.buttons,clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,timeStamp:a.timeStamp},d)}_OnMouseEventAsPointer(b,a){if(!f(a)){var d=this._mousePointerLastButtons;
"pointerdown"===b&&0!==d?b="pointermove":"pointerup"===b&&0!==a.buttons&&(b="pointermove");this._PostToRuntimeMaybeSync(b,{pointerId:1,pointerType:"mouse",button:a.button,buttons:a.buttons,lastButtons:d,clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:a.timeStamp},k);this._mousePointerLastButtons=a.buttons;this._OnMouseEvent(a.type,a,m)}}_OnPointerEvent(b,a){this._pointerRawUpdateRateLimiter&&"pointermove"!==
b&&this._pointerRawUpdateRateLimiter.Reset();var d=0;"mouse"===a.pointerType&&(d=this._mousePointerLastButtons);this._PostToRuntimeMaybeSync(b,{pointerId:a.pointerId,pointerType:a.pointerType,button:a.button,buttons:a.buttons,lastButtons:d,clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,width:a.width||0,height:a.height||0,pressure:a.pressure||0,tangentialPressure:a.tangentialPressure||0,tiltX:a.tiltX||0,tiltY:a.tiltY||0,twist:a.twist||0,timeStamp:a.timeStamp},k);"mouse"===a.pointerType&&
(d="mousemove","pointerdown"===b?d="mousedown":"pointerup"===b&&(d="mouseup"),this._OnMouseEvent(d,a,m),this._mousePointerLastButtons=a.buttons)}_OnPointerRawUpdate(b){this._lastPointerRawUpdateEvent=b;this._pointerRawUpdateRateLimiter.Call()}_DoSendPointerRawUpdate(){this._OnPointerEvent("pointermove",this._lastPointerRawUpdateEvent);this._lastPointerRawUpdateEvent=null}_OnTouchEvent(b,a){for(let d=0,e=a.changedTouches.length;d<e;++d){const h=a.changedTouches[d];this._PostToRuntimeMaybeSync(b,{pointerId:h.identifier,
pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:2*(h.radiusX||h.webkitRadiusX||0),height:2*(h.radiusY||h.webkitRadiusY||0),pressure:h.force||h.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:h.rotationAngle||0,timeStamp:a.timeStamp},k)}}_HandlePointerDownFocus(b){window!==window.top&&window.focus();this._IsElementCanvasOrDocument(b.target)&&document.activeElement&&!this._IsElementCanvasOrDocument(document.activeElement)&&
document.activeElement.blur()}_IsElementCanvasOrDocument(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}_AttachDeviceOrientationEvent(){this._attachedDeviceOrientationEvent||(this._attachedDeviceOrientationEvent=!0,window.addEventListener("deviceorientation",b=>this._OnDeviceOrientation(b)),window.addEventListener("deviceorientationabsolute",b=>this._OnDeviceOrientationAbsolute(b)))}_AttachDeviceMotionEvent(){this._attachedDeviceMotionEvent||(this._attachedDeviceMotionEvent=
!0,window.addEventListener("devicemotion",b=>this._OnDeviceMotion(b)))}_OnDeviceOrientation(b){this.PostToRuntime("deviceorientation",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp,webkitCompassHeading:b.webkitCompassHeading,webkitCompassAccuracy:b.webkitCompassAccuracy},k)}_OnDeviceOrientationAbsolute(b){this.PostToRuntime("deviceorientationabsolute",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp},k)}_OnDeviceMotion(b){let a=
null;var d=b.acceleration;d&&(a={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=b.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;const h=b.rotationRate;h&&(e={alpha:h.alpha||0,beta:h.beta||0,gamma:h.gamma||0});this.PostToRuntime("devicemotion",{acceleration:a,accelerationIncludingGravity:d,rotationRate:e,interval:b.interval,timeStamp:b.timeStamp},k)}_OnUpdateCanvasSize(b){const a=this.GetRuntimeInterface(),d=a.GetCanvas();d.style.width=b.styleWidth+"px";d.style.height=b.styleHeight+
"px";d.style.marginLeft=b.marginLeft+"px";d.style.marginTop=b.marginTop+"px";a.MaybeForceBodySize();this._isFirstSizeUpdate&&(d.style.display="",this._isFirstSizeUpdate=!1)}_OnInvokeDownload(b){const a=b.url;b=b.filename;const d=document.createElement("a"),e=document.body;d.textContent=b;d.href=a;d.download=b;e.appendChild(d);d.click();e.removeChild(d)}async _OnRasterSvgImage(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);
a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async _OnGetSvgImageSize(b){return await self.C3_GetSvgImageSize(b.blob)}async _OnAddStylesheet(b){await u(b.url)}_PlayPendingMedia(){var b=[...this._mediaPendingPlay];this._mediaPendingPlay.clear();if(!this._isSilent)for(const a of b)(b=a.play())&&b.catch(d=>{this._mediaRemovedPendingPlay.has(a)||this._mediaPendingPlay.add(a)})}TryPlayMedia(b){if("function"!==typeof b.play)throw Error("missing play function");
this._mediaRemovedPendingPlay.delete(b);let a;try{a=b.play()}catch(d){this._mediaPendingPlay.add(b);return}a&&a.catch(d=>{this._mediaRemovedPendingPlay.has(b)||this._mediaPendingPlay.add(b)})}RemovePendingPlay(b){this._mediaPendingPlay.delete(b);this._mediaRemovedPendingPlay.add(b)}SetSilent(b){this._isSilent=!!b}_OnHideCordovaSplash(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}_OnDebugHighlight(b){if(b.show){this._debugHighlightElem||(this._debugHighlightElem=
document.createElement("div"),this._debugHighlightElem.id="inspectOutline",document.body.appendChild(this._debugHighlightElem));var a=this._debugHighlightElem;a.style.display="";a.style.left=b.left-1+"px";a.style.top=b.top-1+"px";a.style.width=b.width+2+"px";a.style.height=b.height+2+"px";a.textContent=b.name}else this._debugHighlightElem&&(this._debugHighlightElem.style.display="none")}_OnRegisterSW(){window.C3_RegisterSW&&window.C3_RegisterSW()}_OnPostToDebugger(b){window.c3_postToMessagePort&&
(b.from="runtime",window.c3_postToMessagePort(b))}_InvokeFunctionFromJS(b,a){return this.PostToRuntimeAsync("js-invoke-function",{name:b,params:a})}_OnAlert(b){alert(b.message)}})}"use strict";
self.JobSchedulerDOM=class{constructor(c){this._runtimeInterface=c;this._baseUrl=c.GetBaseURL();"preview"===c.GetExportType()?this._baseUrl+="c3/workers/":this._baseUrl+=c.GetScriptFolder();this._maxNumWorkers=Math.min(navigator.hardwareConcurrency||2,16);this._dispatchWorker=null;this._jobWorkers=[];this._outputPort=this._inputPort=null}async Init(){if(this._hasInitialised)throw Error("already initialised");this._hasInitialised=!0;var c=this._runtimeInterface._GetWorkerURL("dispatchworker.js");this._dispatchWorker=
await this._runtimeInterface.CreateWorker(c,this._baseUrl,{name:"DispatchWorker"});c=new MessageChannel;this._inputPort=c.port1;this._dispatchWorker.postMessage({type:"_init","in-port":c.port2},[c.port2]);this._outputPort=await this._CreateJobWorker()}async _CreateJobWorker(){const c=this._jobWorkers.length;var f=this._runtimeInterface._GetWorkerURL("jobworker.js");f=await this._runtimeInterface.CreateWorker(f,this._baseUrl,{name:"JobWorker"+c});const g=new MessageChannel,k=new MessageChannel;this._dispatchWorker.postMessage({type:"_addJobWorker",
port:g.port1},[g.port1]);f.postMessage({type:"init",number:c,"dispatch-port":g.port2,"output-port":k.port2},[g.port2,k.port2]);this._jobWorkers.push(f);return k.port1}GetPortData(){return{inputPort:this._inputPort,outputPort:this._outputPort,maxNumWorkers:this._maxNumWorkers}}GetPortTransferables(){return[this._inputPort,this._outputPort]}};"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.RuntimeInterface({useWorker:!1,workerMainUrl:"workermain.js",engineScripts:["scripts/c3runtime.js"],projectScripts:[],mainProjectScript:"",scriptsType:"classic",scriptFolder:"scripts/",workerDependencyScripts:[],exportType:"html5"}));"use strict";
{function c(g){g.stopPropagation()}function f(g){13!==g.which&&27!==g.which&&g.stopPropagation()}self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(g){super(g,"text-input");this.AddDOMElementMessageHandler("scroll-to-bottom",k=>this._OnScrollToBottom(k))}CreateElement(g,k){let m;const r=k.type;"textarea"===r?(m=document.createElement("textarea"),m.style.resize="none"):(m=document.createElement("input"),m.type=r);m.style.position="absolute";m.autocomplete="off";
m.addEventListener("touchstart",c);m.addEventListener("touchmove",c);m.addEventListener("touchend",c);m.addEventListener("mousedown",c);m.addEventListener("mouseup",c);m.addEventListener("keydown",f);m.addEventListener("keyup",f);m.addEventListener("click",u=>{u.stopPropagation();this._PostToRuntimeElementMaybeSync("click",g)});m.addEventListener("dblclick",u=>{u.stopPropagation();this._PostToRuntimeElementMaybeSync("dblclick",g)});m.addEventListener("input",()=>this.PostToRuntimeElement("change",
g,{text:m.value}));k.id&&(m.id=k.id);this.UpdateState(m,k);return m}UpdateState(g,k){g.value=k.text;g.placeholder=k.placeholder;g.title=k.title;g.disabled=!k.isEnabled;g.readOnly=k.isReadOnly;g.spellcheck=k.spellCheck;k=k.maxLength;0>k?g.removeAttribute("maxlength"):g.setAttribute("maxlength",k)}_OnScrollToBottom(g){g.scrollTop=g.scrollHeight}})}"use strict";
{function c(f){f.stopPropagation()}self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(f){super(f,"button")}CreateElement(f,g){const k=document.createElement("input");var m=k;g.isCheckbox?(k.type="checkbox",m=document.createElement("label"),m.appendChild(k),m.appendChild(document.createTextNode("")),m.style.fontFamily="sans-serif",m.style.userSelect="none",m.style.webkitUserSelect="none",m.style.display="inline-block",m.style.color="black"):k.type="button";m.style.position=
"absolute";m.addEventListener("touchstart",c);m.addEventListener("touchmove",c);m.addEventListener("touchend",c);m.addEventListener("mousedown",c);m.addEventListener("mouseup",c);m.addEventListener("keydown",c);m.addEventListener("keyup",c);k.addEventListener("click",()=>this._PostToRuntimeElementMaybeSync("click",f,{isChecked:k.checked}));g.id&&(k.id=g.id);this.UpdateState(m,g);return m}_GetInputElem(f){return"input"===f.tagName.toLowerCase()?f:f.firstChild}_GetFocusElement(f){return this._GetInputElem(f)}UpdateState(f,
g){const k=this._GetInputElem(f);k.checked=g.isChecked;k.disabled=!g.isEnabled;f.title=g.title;f===k?k.value=g.text:f.lastChild.textContent=g.text}})}"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(c){super(c,"browser");this._exportType="";this.AddRuntimeMessageHandlers([["get-initial-state",f=>this._OnGetInitialState(f)],["ready-for-sw-messages",()=>this._OnReadyForSWMessages()],["alert",f=>this._OnAlert(f)],["close",()=>this._OnClose()],["set-focus",f=>this._OnSetFocus(f)],["vibrate",f=>this._OnVibrate(f)],["lock-orientation",f=>this._OnLockOrientation(f)],["unlock-orientation",()=>this._OnUnlockOrientation()],
["navigate",f=>this._OnNavigate(f)],["request-fullscreen",f=>this._OnRequestFullscreen(f)],["exit-fullscreen",()=>this._OnExitFullscreen()],["set-hash",f=>this._OnSetHash(f)]]);window.addEventListener("online",()=>this._OnOnlineStateChanged(!0));window.addEventListener("offline",()=>this._OnOnlineStateChanged(!1));window.addEventListener("hashchange",()=>this._OnHashChange());document.addEventListener("backbutton",()=>this._OnCordovaBackButton());"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",
f=>this._OnWin10BackRequested(f))}_OnGetInitialState(c){this._exportType=c.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}_OnReadyForSWMessages(){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(c=>
this.PostToRuntime("sw-message",c.data))}_OnOnlineStateChanged(c){this.PostToRuntime("online-state",{isOnline:c})}_OnCordovaBackButton(){this.PostToRuntime("backbutton")}_OnWin10BackRequested(c){c.handled=!0;this.PostToRuntime("backbutton")}GetNWjsWindow(){return"nwjs"===this._exportType?nw.Window.get():null}_OnAlert(c){alert(c.message)}_OnClose(){navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}_OnSetFocus(c){c=
c.isFocus;if("nwjs"===this._exportType){const f=this.GetNWjsWindow();c?f.focus():f.blur()}else c?window.focus():window.blur()}_OnVibrate(c){navigator.vibrate&&navigator.vibrate(c.pattern)}_OnLockOrientation(c){c=c.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(f=>console.warn("[Construct 3] Failed to lock orientation: ",f));else try{let f=!1;screen.lockOrientation?f=screen.lockOrientation(c):screen.webkitLockOrientation?f=screen.webkitLockOrientation(c):
screen.mozLockOrientation?f=screen.mozLockOrientation(c):screen.msLockOrientation&&(f=screen.msLockOrientation(c));f||console.warn("[Construct 3] Failed to lock orientation")}catch(f){console.warn("[Construct 3] Failed to lock orientation: ",f)}}_OnUnlockOrientation(){try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():
screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(c){}}_OnNavigate(c){var f=c.type;if("back"===f)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.back();else if("forward"===f)window.forward();else if("home"===f)window.home();else if("reload"===f)location.reload();else if("url"===f){f=c.url;var g=c.target;c=c.exportType;"windows-uwp"===c&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(f)):self.cordova&&self.cordova.InAppBrowser?
self.cordova.InAppBrowser.open(f,"_system"):"preview"===c?window.open(f,"_blank"):this._isScirraArcade||(2===g?window.top.location=f:1===g?window.parent.location=f:window.location=f)}else"new-window"===f&&(f=c.url,g=c.tag,"windows-uwp"===c.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(f)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(f,"_system"):window.open(f,g))}_OnRequestFullscreen(c){const f={navigationUI:"auto"};
c=c.navUI;1===c?f.navigationUI="hide":2===c&&(f.navigationUI="show");c=document.documentElement;c.requestFullscreen?c.requestFullscreen(f):c.mozRequestFullScreen?c.mozRequestFullScreen(f):c.msRequestFullscreen?c.msRequestFullscreen(f):c.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?c.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):c.webkitRequestFullScreen())}_OnExitFullscreen(){document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():
document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}_OnSetHash(c){location.hash=c.hash}_OnHashChange(){this.PostToRuntime("hashchange",{location:location.toString()})}});"use strict";self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(c){super(c,"mouse");this.AddRuntimeMessageHandler("cursor",f=>this._OnChangeCursorStyle(f))}_OnChangeCursorStyle(c){document.documentElement.style.cursor=c}});"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(c){super(c,"touch");this.AddRuntimeMessageHandler("request-permission",f=>this._OnRequestPermission(f))}async _OnRequestPermission(c){c=c.type;let f=!0;0===c?f=await this._RequestOrientationPermission():1===c&&(f=await this._RequestMotionPermission());this.PostToRuntime("permission-result",{type:c,result:f})}async _RequestOrientationPermission(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;
try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(c){return console.warn("[Touch] Failed to request orientation permission: ",c),!1}}async _RequestMotionPermission(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(c){return console.warn("[Touch] Failed to request motion permission: ",c),!1}}});
